project:
  mode: release
  name: detectionx
  version: 1.0.0
  describe: ""

detection:
  model_path: "asset/models/detection/yolo11/coco/rk3588/detection_yolo11s_coco_int8.rknn"
  num_workers: 3
  threshold: 0.6
  classes:

mqtt:
  enable: false
  ip: localhost
  port: 1883
  interval: 500 # ms
  notify_topic: /perception/detectionx/results

rtsp:
  port: 16888
  width: 1280
  height: 720
  suffix: detectionx

# tasks: 任务列表，每个任务对应一路视频源
#
# region.type 支持三种区域定义方式：
#   - ratio   : 四边相对边缘的比例区域
#               values = [left, top, right, bottom], 取值范围 [0, 1)
#
#   - xyxy    : 像素坐标矩形区域
#               values = [x1, y1, x2, y2]
#
#   - polygon : 多边形区域（像素坐标）
#               values = [ [x1, y1], [x2, y2], ... ]
#
tasks:
  - id: cam00001
    uri: /home/firefly/Videos/1.mp4
    region:
      type: polygon
      values: [ [280, 340], [860, 342], [1350, 610], [3, 628], [3, 495], [14, 491] ]

  - id: cam00002
    uri: /home/firefly/Videos/2.mp4
    region:
      type: polygon
      values: [ [233, 300], [1000, 296], [1276, 440], [1276, 600], [3, 560], [3, 425] ]

#  - id: cam00003
#    uri: /home/firefly/Videos/3.mp4
#    region:
#      type: ratio
#      values: [ 0.2, 0.2, 0.2, 0.2 ]
#
#  - id: cam00004
#    uri: /home/firefly/Videos/4.mp4
#    region:
#      type: ratio
#      values: [ 0.2, 0.2, 0.2, 0.2 ]
#
#  - id: cam00005
#    uri: /home/firefly/Videos/5.mp4
#    region:
#      type: ratio
#      values: [ 0.2, 0.2, 0.2, 0.2 ]
#
#  - id: cam00006
#    uri: /home/firefly/Videos/6.mp4
#    region:
#      type: ratio
#      values: [ 0.2, 0.2, 0.2, 0.2 ]

#  - id: cam00002
#    uri: /dev/video1
#    region:
#      type: xyxy
#      values: [ 100, 100, 200, 300 ]

#  - id: cam00003
#    uri: /dev/video2
#    region:
#      type: polygon
#      values:
#        - [ 100, 100 ]
#        - [ 300, 100 ]
#        - [ 350, 300 ]
