set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN_ROOT /home/$ENV{USER}/coder/envs/gcc/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_ROOT}/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_ROOT}/aarch64-linux-gnu-g++)

# set(CMAKE_SYSROOT /path/to/your/sysroot)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)