set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_ROOT /home/$ENV{USER}/coder/envs/gcc/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_ROOT}/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_ROOT}/arm-linux-gnueabihf-g++)

# set(CMAKE_SYSROOT /path/to/your/sysroot)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)